### ISSUE TITLE
How I can  add this flag to my compile options esp8266

### ISSUE THREAD

**Issue by mrdsn3** [davetcc/TaskManagerIO#31]
How I can  add this flag to my compile options  DTM_ENABLE_CAPTURED_LAMBDAS

**Comment by davetcc** [comment]
Depends on the IDE and build tool basically. 

You need to add a compiler define flag. For example in platformIO you add build_flags to a target as per: https://github.com/davetcc/tcLibraryDev/blob/master/platformio.ini

While regular Arduino IDE does not support build flags directly, you would need to manually set it in the file.

**Comment by davetcc** [comment]
BTW the flag is TM_ENABLE_CAPTURED_LAMBDAS the -D at the beginning is the option for setting a flag in gcc.

**Comment by mrdsn3** [comment]
thanks  so is this code added the flag? is this right?
`#include <TaskManagerIO.h>
#if !defined(TM_ENABLE_CAPTURED_LAMBDAS)
# define TM_ALLOW_CAPTURED_LAMBDA
#endif
void setup() {
  // put your setup code here, to run once:

}

void loop() {
  // put your main code here, to run repeatedly:

}`

**Comment by davetcc** [comment]
Unfortunately for Arduino IDE it has to go into TaskPlatformDeps.h, otherwise it will not be picked up when compiling the library.

If you are using the pro IDE, Eclipse, or platformIO you can define the flag in the build tool.

**Comment by mrdsn3** [comment]
OK thanks
