### ISSUE TITLE
Warning messages in DfRobotInputAbstraction.h and IoAbstraction.h

### ISSUE THREAD

**Issue by fletchjp** [davetcc/TaskManagerIO#36]
I have turned on warnings in the Arduino IDE and it comes up with some warnings for these files, all of which are [-Wunused-parameter] and easy to fix by commenting out the name of the parameter. I have uploaded a zip with the two changed files.

Thank you for your libraries

John Fletcher

[ChangedFiles.zip](https://github.com/davetcc/TaskManagerIO/files/7803066/ChangedFiles.zip)

**Comment by davetcc** [comment]
These are acutally in IoAbstraction.

Most of our development is using CLion on platformIO, we have code linting turned on, but it probably has a slightly different set of warnings to Arduino IDE. However, I've gone through and tried to fix up as many warnings as I can.
