### ISSUE TITLE
Page link dead

### ISSUE THREAD

**Issue by tomelgato** [davetcc/TaskManagerIO#50]
Not sure if this is the right place but:

https://www.thecoderscorner.com/products/arduino-libraries/io-abstraction/

The [Read the reference guide](https://www.thecoderscorner.com/ref-docs/ioabstraction/html/index.html) link points to an empty page

P.S. Does IOAbstraction use any of the Arduino interrupt timers?

**Comment by davetcc** [comment]
It's actually not a dead link, it's the reference docs, the doxygen layout I'm using is just not very good and needs to be improved, if you click on any of the menu options you'll see what I mean. I need to look at how to get a better front page.
